[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "task-cli-master"
version = "0.1.0"
description = "A modern, interactive CLI & TUI task management system built with python"
readme = "README.md"
requires.python = ">=3.11"
authors = [
    { name = "Mahdi" }
]
dependencies = [
    "pydantic>=2.7.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-cov>=5.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v"
